### ISSUE TITLE
Keep original vsftpd.conf file on system for reference 

### ISSUE THREAD

**Issue by poliva83** [flatrocks/cookbook-basic_vsftpd#1]
The original `vsftpd.conf` file is actually well documented and useful to keep on server for reference purposes. My suggestion is 1st time vsftpd package is installed we move the original `vsftpd.conf` file to `/etc/vsftpd.conf.orig`.

**Comment by flatrocks** [comment]
A fine idea.  The original file may be useful in addition to the [vsftpd docs.](https://security.appspot.com/vsftpd/vsftpd_conf.html)

Thanks @poliva83 for including clean tests.
